import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full px-4 py-3 bg-gray-100 border-b flex items-center justify-between">
          <span className="font-bold text-lg">Steam Achievements Tracker</span>
          <a href="/auth" className="text-blue-600 hover:underline">Login / Register</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
